services:
  db:
    container_name: postgres
    image: postgres:14.7
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  ultrasur-springboot:
    container_name: ultrasur-springboot
    image: ultrasur/spring-boot-fullstack-professional
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - 8088:8080
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  ultrasur-frontend-react:
    container_name: ultrasur-react
    image: ultrasur/ultrasur-react
    build:
#      where to find Dockerfile
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - ultrasur-springboot
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: